---
# tasks file for mongodb

- name: Add Mongodb repo to yum repo
  template:
    src: mongodb_repo.j2
    dest: /etc/yum.repos.d/mongodb-org.repo
  become: yes

- name: Install mongodb
  yum:
    name: mongodb-org
    state: present
  become: yes

- name: start mongo
  systemd:
    name: mongod
    state: started

- name: Enable replication in mongodb
  template:
    src: mongodb_replica.j2
    dest: /etc/mongod.conf

- name: Restart mongo
  systemd:
    name: mongod
    state: restarted

- name: Create a file to Initialize replication
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  when: inventory_hostname in groups['mongo_master']

- name: Initialize the replication set
  shell: /usr/bin/mongo /tmp/repset_init.js
  when: inventory_hostname in groups['mongo_master']


- name: Create a file to set slave
  template: src=set_slave.j2 dest=/tmp/set_slave.js
  when: inventory_hostname in groups['mongo_slave']

- name: Check Slave ok
  shell: /usr/bin/mongo /tmp/set_slave.js
  when: inventory_hostname in groups['mongo_slave']



