---
# tasks file for mongodb

- name: Add Mongodb repo to yum repo
  template:
    src: mongodb_repo.j2
    dest: /etc/yum.repos.d/mongodb-org.{{ version }}.repo

- name: Install mongodb
  yum:
    name: mongodb-org
    state: present


- name: Enable replication in mongodb
  template:
    src: mongodb_replica.j2
    dest: /etc/mongod.conf

- name: Start mongo
  systemd:
    name: mongod
    state: started
    enabled: yes

- name: Create a file to Initialize replication
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  when: inventory_hostname in groups['mongo_master']

- name: Create a file to Create Admin user
  template: src=mongo_adminuser.j2 dest=/tmp/mongo_adminuser.js
  when: inventory_hostname in groups['mongo_master']


- name: Initialize the replication set
  shell: /usr/bin/mongo /tmp/repset_init.js
  register: rep_initiate
  when: inventory_hostname in groups['mongo_master']

- debug:
      var: rep_initiate


- name: Create admin user
  shell: /usr/bin/mongo < /tmp/mongo_adminuser.js
  register: create_user
  when: inventory_hostname in groups['mongo_master']


- name: Create a file to set slave
  template: src=set_slave.j2 dest=/tmp/set_slave.js
  when: inventory_hostname in groups['mongo_slave']

- name: Check Slave ok
  shell: /usr/bin/mongo /tmp/set_slave.js
  register: slave_initiate
  when: inventory_hostname in groups['mongo_slave']

- debug:
      var: slave_initiate

- name: Enable authorization
  template:
    src: mongo_authhorization.j2
    dest: /etc/mongod.conf
