---
- name: Establish some role-related facts
  set_fact:
    mongo_major_version: "{{ mongo_version[0:3] }}"

- name: Install EPEL release repository on RHEL
  yum:
    name: "{{ epel_release_rpm }}"
    state: present
    update_cache: true
  when: ansible_distribution == "RedHat"

- name: Install EPEL release repository on Centos
  yum:
    name: epel-release
    state: present
    update_cache: true
  when: ansible_distribution == "Centos"

- name: Add Mongo repository
  template:
    src: mongo_repo.j2
    dest: /etc/yum.repos.d/mongodb.repo
    mode: 0644

- name: Install MongoDB package
  yum:
    name: "{{ mongo_package_name }}{% if (mongo_version | length > 3) %}-{{ mongo_version }}{% endif %}"
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"

- name: Install PIP
  yum:
    name:
      - python{{ ansible_python['version']['major'] }}-devel
      - python{{ ansible_python['version']['major'] }}-pip
    lock_timeout: "{{ yum_lock_timeout }}"

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    state: "{{ pymongo_pip_version is defined | ternary('present','latest') }}"
    version: "{{ pymongo_pip_version | default(omit) }}"
