---
- name: Setup Mongo service file
  template:
    src: mongo_service_file.j2
    dest: /lib/systemd/system/{{ mongo_service_name }}.service
    mode: 0644
    owner: root
    group: root
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - reload_systemd

- name: Add symlink for systemd
  file:
    src: /lib/systemd/system/{{ mongo_service_name }}.service
    dest: /etc/systemd/system/multi-user.target.wants/{{ mongo_service_name }}.service
    state: link
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - reload_systemd

- name: Flush all handlers at this point
  meta: flush_handlers

- name: Enable mongo service
  service:
    name: "{{ mongo_service_name }}"
    enabled: "yes"
